export const GET_PROJECT_BY_TITLE = "GET_PROJECT_BY_TITLE";
export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const LOGIN = "LOGIN";
export const SEND_MAIL = "SEND_MAIL";
export const PROJECT_BY_ID = "PROJECT_BY_ID";
export const CLEAR_PROJECT_BY_ID = "CLEAR_PROJECT_BY_ID";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const GET_LOCATION = "GET_LOCATION";



